name: Projekt_Kontener CI Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-container-engine:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Pobranie kodu repozytorium
      uses: actions/checkout@v4

    - name: âš™ï¸ Weryfikacja Å›rodowiska
      run: |
        python3 --version
        make --version

    - name: ğŸš€ Prowizjonowanie Å›rodowiska
      run: make prepare

    - name: ğŸ§ª Test automatyczny izolacji i sieci
      run: make test
